import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  fr: {
    // ── Navbar / Generic ─────────────────────────────────────────────────────
    landingPage: "Accueil du Congrès",
    workspaceDashboard: "Espace de Travail",
    signOut: "Se déconnecter",
    signIn: "Se connecter",
    register: "Créer un compte",
    role: "Rôle",
    status: "Statut",
    welcome: "Bienvenue",
    contextSelector: "Contexte de travail",
    notifications: "Notifications",
    pendingMeetings: "demandes de réunion en attente",
    language: "Langue",
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    search: "Rechercher",
    export: "Exporter",
    import: "Importer",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    confirm: "Confirmer",
    close: "Fermer",
    send: "Envoyer",
    assign: "Affecter",
    validate: "Valider",
    reject: "Rejeter",
    approve: "Approuver",
    download: "Télécharger",
    upload: "Déposer",
    preview: "Aperçu",
    submit: "Soumettre",
    actions: "Actions",
    loading: "Chargement...",
    noResults: "Aucun résultat trouvé.",
    
    // ── Status Labels ─────────────────────────────────────────────────────────
    statusSubmitted: "Soumission Initiale",
    statusUnderReview: "En Cours d'Évaluation",
    statusReviewed: "Évalué",
    statusReviewDispatched: "Rapport Envoyé à l'Auteur",
    statusRevisionSubmitted: "Révision Déposée",
    statusAccepted: "Accepté",
    statusRejected: "Rejeté",
    statusPending: "En Attente",
    statusActive: "Actif",
    statusSuspended: "Suspendu",
    statusOpen: "Ouvert",
    statusClosed: "Clôturé",
    statusApproved: "Approuvé",
    
    // ── Auth Modal ────────────────────────────────────────────────────────────
    loginTitle: "Connexion",
    registerTitle: "Inscription",
    emailLabel: "Adresse E-mail",
    passwordLabel: "Mot de passe",
    nameLabel: "Nom Complet",
    affiliationLabel: "Institution d'Affiliation",
    roleLabel: "Rôle Demandé",
    conferenceLabel: "Sélectionner le Congrès",
    submitBtn: "Valider",
    loginError: "Email ou mot de passe incorrect.",
    loginSuccess: "Connexion réussie !",
    authTitle: "Authentification Sympovex",
    awaitingValTitle: "En attente de validation",
    awaitingValDesc: "Votre demande d'inscription est en attente de validation par l'administrateur. Vous pourrez vous connecter une fois activé.",
    submitReg: "Soumettre l'inscription",
    regSuccessTitle: "Demande d'inscription reçue",
    regSuccessDesc: "Votre demande d'inscription a été enregistrée avec succès. Un administrateur l'examinera et la validera avant que vous ne puissiez vous connecter.",
    createAccount: "Créer un compte",
    
    // ── Dashboard Hub ─────────────────────────────────────────────────────────
    accessRestricted: "Accès à l'Espace Restreint",
    selectRoleTitle: "Sélectionnez votre Espace de Travail",
    enterWorkspace: "Entrer dans l'espace",
    forcePasswordTitle: "Définir un Nouveau Mot de Passe",
    forcePasswordDesc: "Votre compte a été créé par un administrateur. Vous devez définir un nouveau mot de passe avant de continuer.",
    newPasswordLabel: "Nouveau Mot de Passe",
    confirmPasswordLabel: "Confirmer le Mot de Passe",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordTooShort: "Le mot de passe doit comporter au moins 8 caractères.",
    passwordChanged: "Mot de passe mis à jour avec succès.",
    
    // ── Participant / Author Dashboard ────────────────────────────────────────
    participantConsole: "Espace Auteur & Participant",
    participantDesc: "Soumettez vos articles, déposez vos révisions, interagissez avec les participants et consultez l'état de vos soumissions.",
    newSubmission: "Nouvelle Soumission d'Article",
    paperTitle: "Titre de l'article",
    abstract: "Résumé (Abstract)",
    keywords: "Mots-clés (Keywords)",
    authorsList: "Matrice des Auteurs",
    paperType: "Format de Soumission",
    shortPaper: "Short Paper (Communication courte)",
    extendedPaper: "Extended Paper (Article complet)",
    poster: "Poster",
    submitSuccess: "Votre manuscrit a été soumis avec succès !",
    submitSuccessId: "Référence enregistrée :",
    submitSuccessEmail: "Un email de confirmation a été envoyé à votre adresse.",
    mySubmissions: "Mes Soumissions & Statuts",
    proceedingsDownload: "Actes Officiels du Congrès",
    proceedingsDesc: "Téléchargez l'intégralité des articles acceptés et le recueil des résumés officiels (Proceedings).",
    proceedingsBtn: "Télécharger Proceedings",
    submissionGuidelines: "Consignes de Soumission (Guidelines)",
    selectTopics: "Thématiques Scientifiques (au moins 1)",
    attachFile: "Déposer votre manuscrit (.pdf, .docx, .tex)",
    addAuthor: "Ajouter un auteur",
    removeAuthor: "Retirer",
    authorName: "Nom de l'auteur",
    authorAffiliation: "Institution",
    authorEmail: "Email de l'auteur",
    fileError: "Format de fichier invalide. Accepté : .pdf, .docx, .tex, .doc",
    
    // ── Participant — Review dispatch banner ──────────────────────────────────
    reviewDispatchedBanner: "📩 Le Comité Scientifique a validé et envoyé votre rapport d'évaluation.",
    reviewDispatchedAction: "Vous pouvez désormais soumettre une version corrigée de votre article.",
    uploadRevisionBtn: "Déposer une Version Corrigée",
    uploadRevisionTitle: "Dépôt de Version Révisée",
    uploadRevisionSuccess: "Révision V{n} enregistrée avec succès ! Le comité a été notifié.",
    
    // ── Participant — Survey ───────────────────────────────────────────────────
    surveyTitle: "Questionnaire de Satisfaction",
    surveyDesc: "Partagez votre expérience avec le comité organisateur.",
    surveyOrgLabel: "Organisation & Logistique (1–5)",
    surveyContentLabel: "Qualité Scientifique & Contenu (1–5)",
    surveyCommentsLabel: "Commentaires libres",
    surveySubmitBtn: "Envoyer mon avis",
    surveySuccess: "Merci ! Votre questionnaire a été enregistré.",
    
    // ── Participant — Gallery ─────────────────────────────────────────────────
    galleryUpload: "Envoyer des Photos en Temps Réel",
    galleryDesc: "Partagez vos photos de l'événement (soumises à approbation du comité).",
    galleryCaptionLabel: "Légende de la photo",
    gallerySubmitBtn: "Envoyer pour modération",
    gallerySuccess: "Photo soumise ! En attente d'approbation.",
    
    // ── Participant — Vote ────────────────────────────────────────────────────
    voteTitle: "Vote du Public",
    bestPosterVote: "Voter pour le Meilleur Poster",
    bestOralVote: "Voter pour la Meilleure Présentation Orale",
    voteSuccess: "Votre vote a été enregistré !",
    alreadyVoted: "Vous avez déjà voté dans cette catégorie.",
    
    // ── Participant — Networking ──────────────────────────────────────────────
    networkingTitle: "Réseautage & Messagerie",
    chatWith: "Chatter avec",
    sendMessage: "Envoyer le message",
    scheduleSlot: "Planifier une rencontre",
    meetingPurpose: "Objet de la réunion",
    meetingDate: "Date/heure souhaitée",
    scheduleMeetingBtn: "Demander un créneau",
    meetingSuccess: "Demande de réunion envoyée !",
    
    // ── Participant — Tickets ─────────────────────────────────────────────────
    supportTickets: "Mes Tickets de Support",
    newTicket: "Nouveau Ticket",
    ticketSubject: "Sujet du ticket",
    ticketCategory: "Catégorie",
    ticketMessage: "Message détaillé",
    ticketSubmitBtn: "Envoyer le ticket",
    ticketSuccess: "Ticket ouvert avec succès.",
    ticketReply: "Répondre",
    
    // ── Reviewer Dashboard ────────────────────────────────────────────────────
    reviewerConsole: "Console d'Évaluation Académique",
    reviewerDesc: "Consultez vos articles assignés, soumettez vos rapports d'évaluation détaillés et suivez l'avancement.",
    assignedPapers: "Articles Assignés",
    evaluateBtn: "Évaluer l'article",
    scoreCriteria: "Critères de notation",
    commentsFormLabel: "Remarques de Forme (Mise en page, structure)",
    commentsSciLabel: "Remarques Scientifiques (Contenu, méthodologie)",
    presentationFormat: "Format de présentation recommandé",
    oralFormat: "Présentation Orale",
    posterFormat: "Présentation Poster",
    attachCommentsFile: "Joindre un fichier de commentaires (.pdf / .docx)",
    reviewSubmitBtn: "Soumettre le Rapport d'Évaluation",
    reviewSuccess: "Rapport d'évaluation soumis avec succès !",
    alreadyReviewed: "Vous avez déjà soumis un rapport pour cet article.",
    noAssignedPapers: "Aucun article ne vous a encore été assigné.",
    viewScoreCard: "Voir la fiche d'évaluation",
    readOnlyReview: "Rapport Soumis (Lecture Seule)",
    closePane: "Fermer le panneau",
    selectManuscriptPrompt: "Sélectionnez un article dans la liste de gauche pour commencer votre évaluation.",
    choosePhotoSubmit: "Choisissez une photo à soumettre",
    photoCaptionPlaceholder: "Ex. Session plénière ou networking",
    noAssignedPapersTrack: "Aucun manuscrit n'est affecté à votre profil de track.",
    originalityNovelty: "Originalité & Nouveauté",
    methodologyRigor: "Méthodologie & Rigueur",

    // ── Global Portal ──────────────────────────────────────────────────────────
    portalTitle: "Plateforme Premium SaaS pour Congrès Scientifiques",
    portalSub: "Gérez les soumissions, relisez les articles en double aveugle, animez le networking et analysez la satisfaction en temps réel.",
    activeCongresses: "Congrès Actifs",
    archivedCongresses: "Congrès Archivés",
    enterCongress: "Entrer sur le site →",
    viewArchives: "Consulter les archives",
    platformFeatures: "Fonctionnalités de la Plateforme",
    featureMultiTenant: "Multi-Tenant",
    featureMultiTenantDesc: "Hébergez plusieurs congrès indépendants avec chartes graphiques et bases de données étanches.",
    featureTranslation: "Traduction Intégrale",
    featureTranslationDesc: "Traduction dynamique en temps réel de tous les textes statiques et dynamiques pour les participants mondiaux.",
    featureReview: "Évaluation en Double Aveugle",
    featureReviewDesc: "Affectation intelligente d'évaluateurs, rapports consolidés et validation par le comité scientifique.",
    featureNetworking: "Réseautage & Galerie",
    featureNetworkingDesc: "Messagerie instantanée, planification de réunions en face-à-face et galerie photo événementielle en direct.",
    viewAllCongresses: "← Tous les Congrès",
    profileTitle: "Votre Profil Utilisateur",
    profileSubtitle: "Mettez à jour vos informations personnelles, votre photo de profil et votre biographie.",
    profileName: "Nom Complet",
    profilePhotoUrl: "URL de la Photo de Profil",
    profileBio: "Description / Biographie",
    profileSaveBtn: "Enregistrer les modifications",
    profileSuccess: "Votre profil a été mis à jour avec succès !",
    profilePresetAvatars: "Ou choisissez un avatar prédéfini",
    backToDashboard: "← Retour au Tableau de Bord",
    profileRole: "Rôle de Compte",
    profileAffiliation: "Affiliation / Université",
    
    // ── PSC Dashboard ─────────────────────────────────────────────────────────
    pscConsole: "Console du Comité Scientifique (PSC)",
    pscDesc: "Supervisez le pipeline scientifique, configurez les thématiques, provisionnez les évaluateurs et validez les rapports d'évaluation.",
    tabPapers: "Soumissions Maîtres",
    tabTopics: "Thématiques (CRUD)",
    tabParticipants: "Annuaire des Participants",
    tabReviewers: "Contrôle des Évaluateurs",
    tabTickets: "Requêtes de Support",
    tabProvisioning: "Provisionnement de Comptes",
    tabGuidelines: "Instructions & Critères",
    
    // PSC — Paper table columns
    colTitleAuthors: "Titre & Auteurs",
    colTopics: "Thématiques",
    colReviewers: "Évaluateurs",
    colAvgScore: "Score Moyen",
    colActions: "Actions",
    colStatus: "Statut",
    colDate: "Date",
    colVersion: "Version",
    colFile: "Fichier",
    
    // PSC — Paper detail drawer
    paperDetail: "Détail de la Soumission",
    paperId: "Référence",
    paperSubmittedOn: "Soumis le",
    paperVersionHistory: "Historique des Versions",
    paperReviewHistory: "Chronologie Complète",
    paperReviewReports: "Rapports d'Évaluation Consolidés",
    pscValidationPanel: "Panel de Validation PSC",
    pscValidationNote: "Note de Validation PSC (optionnel)",
    pscValidationNotePlaceholder: "Ajoutez une note de synthèse visible par l'auteur...",
    validateAndSendBtn: "Valider & Envoyer le Rapport à l'Auteur",
    rejectPaperBtn: "Rejeter la Soumission",
    reportAlreadySent: "✅ Rapport déjà envoyé à l'auteur.",
    noReviewsYet: "Aucun rapport d'évaluation reçu pour cet article.",
    reviewerLabel: "Évaluateur",
    formRemarks: "Remarques de Forme",
    scientificRemarks: "Remarques Scientifiques",
    recommendedFormat: "Format Recommandé",
    overallScore: "Score Global",
    dispatchSuccess: "Rapport validé et envoyé à l'auteur avec succès !",
    dispatchConfirm: "Confirmer l'envoi du rapport d'évaluation à l'auteur ?",
    rejectConfirm: "Confirmer le rejet définitif de cette soumission ?",
    
    // PSC — timeline event labels
    timelineSubmitted: "Soumission reçue",
    timelineReviewerAssigned: "Relecteur(s) assigné(s)",
    timelineReviewReceived: "Rapport reçu",
    timelineReportDispatched: "Rapport envoyé à l'auteur",
    timelineRevisionReceived: "Révision reçue",
    
    // PSC — side panel
    consolidatedReviews: "Rapports Consolidés",
    noReviewsSidePanel: "Aucune évaluation soumise.",
    
    // PSC — Topics
    topicsCrud: "Gestion des Thématiques Scientifiques",
    topicName: "Intitulé de la Thématique",
    topicDescription: "Description (optionnel)",
    addTopicBtn: "Ajouter la Thématique",
    editTopic: "Modifier la Thématique",
    deleteTopicConfirm: "Supprimer cette thématique ?",
    noTopics: "Aucune thématique configurée.",
    
    // PSC — Participants
    participantsDir: "Annuaire des Participants",
    partSearchPlaceholder: "Recherche par nom, email, institution...",
    promoteToReviewer: "Promouvoir en Évaluateur",
    alreadyReviewer: "Déjà Évaluateur",
    exportParticipants: "Exporter CSV",
    importParticipants: "Importer Excel",
    noParticipants: "Aucun participant trouvé.",
    
    // PSC — Reviewer Control
    reviewerControl: "Gestion des Évaluateurs",
    assignPaper: "+ Affecter",
    selectReviewer: "Sélectionner un évaluateur...",
    commitAssignment: "Valider l'affectation",
    noReviewers: "Aucun évaluateur enregistré.",
    
    // PSC — Provisioning
    provisionAccounts: "Provisionner des Comptes",
    provFullName: "Nom Complet",
    provEmail: "Adresse Email",
    provRole: "Rôle",
    provAffiliation: "Institution",
    provPassword: "Mot de Passe Temporaire",
    provBtn: "Créer le Compte",
    provSuccess: "Compte créé. L'utilisateur devra changer son mot de passe à la connexion.",
    
    // PSC — Provisioning Bulk
    bulkProvisionTitle: "Provisionnement en Masse (Excel/CSV)",
    bulkProvisionDesc: "Importez une liste d'utilisateurs depuis un fichier Excel/CSV ou exportez les comptes existants.",
    downloadTemplate: "Télécharger le modèle (.csv)",
    importPlaceholder: "Glissez-déposez ou sélectionnez un fichier CSV...",
    importFileBtn: "Choisir un fichier",
    importSubmitBtn: "Importer et Créer",
    exportPartBtn: "Exporter les Participants",
    exportRevBtn: "Exporter les Évaluateurs",
    exportAllBtn: "Exporter Tous les Comptes",
    importReportSuccess: "Import réussi ! {count} comptes ont été provisionnés.",
    importReportError: "Erreur lors de l'import: {error}",
    
    // PSC — Guidelines & Criteria
    authorInstructions: "Instructions pour les Auteurs (Guidelines)",
    authorInstructionsPlaceholder: "Rédigez les consignes de soumission (format, longueur, style...).",
    saveGuidelines: "Enregistrer les Instructions",
    guidelinesSaved: "Instructions mises à jour avec succès.",
    evaluationCriteria: "Configuration des Critères d'Évaluation",
    critName: "Nom du Critère",
    critMaxScore: "Score Maximum",
    addCritBtn: "Ajouter le Critère",
    noCriteria: "Aucun critère configuré.",
    deleteCritConfirm: "Supprimer ce critère d'évaluation ?",
    
    // ── POC Dashboard ──────────────────────────────────────────────────────────
    pocConsole: "Tableau de Bord du Comité d'Organisation (POC)",
    pocDesc: "Gérez l'organisation, analysez les retours, segmentez les contacts et générez les badges.",
    satisfactionAnalytics: "Analyse Graphique des Questionnaires de Satisfaction",
    avgOrgRating: "Moyenne Organisation",
    avgContentRating: "Moyenne Contenu Scientifique",
    surveyResponses: "réponse(s)",
    segmentationDb: "Segmentation de la Base Contacts",
    filterBySegment: "Filtrer par segment",
    allSegments: "Tous les segments",
    exportFiltered: "Exporter le segment CSV",
    attestationBadge: "Génération de Badges & Attestations",
    selectTemplate: "Sélectionner le modèle",
    generateBtn: "Générer pour tous les participants",
    exportMerge: "Exporter le publipostage",
    voteLeaderboard: "Leaderboard du Vote du Public",
    bestPoster: "Meilleur Poster",
    bestPresentation: "Meilleure Présentation",
    votes: "vote(s)",
    mailingCampaigns: "Campagnes d'E-mailing",
    galleryModeration: "Modération de la Galerie Photo",
    approvePhoto: "Approuver",
    deletePhoto: "Supprimer",
    pendingPhotos: "Photos en attente",
    noPhotos: "Aucune photo soumise.",
    
    // ── Admin / President Dashboard ────────────────────────────────────────────
    adminConsole: "Console Présidente du Congrès",
    adminDesc: "Gérez les inscriptions, la charte graphique et la modération des contenus.",
    brandingConfig: "Configuration de la Charte Graphique",
    primaryColor: "Couleur Primaire",
    secondaryColor: "Couleur Secondaire",
    accentColor: "Couleur d'Accent",
    applyBranding: "Appliquer la Charte",
    pendingValidations: "Validation des Inscriptions en Attente",
    activateUser: "Activer",
    suspendUser: "Suspendre",
    deleteUserConfirm: "Supprimer cet utilisateur ?",
    
    // ── Superadmin Dashboard ───────────────────────────────────────────────────
    superadminConsole: "Console Superadmin — Administration Globale",
    superadminDesc: "Gérez tous les congrès, tous les utilisateurs, les connexions Supabase et la configuration système.",
    supabaseConfig: "Configuration de la Connexion Supabase",
    supabaseUrl: "URL Supabase",
    supabaseKey: "Clé Anonyme (Anon Key)",
    supabaseJwt: "JWT Secret",
    exportSqlSchema: "Exporter le Schéma SQL",
    resetDatabase: "Réinitialiser la Base de Données",
    resetConfirm: "Confirmer la réinitialisation ? Toutes les données seront supprimées.",
    
    // ── Workspace & Dashboard Hub ──
    pwErrorLength: "Le mot de passe doit comporter au moins 6 caractères.",
    pwErrorMatch: "Les mots de passe ne correspondent pas.",
    pwErrorFail: "Impossible de changer le mot de passe. Veuillez contacter le support.",
    secureInterface: "INTERFACE DE L'ESPACE DE TRAVAIL SÉCURISÉ",
    sessionRole: "RÔLE DE SESSION",
    tenantLabel: "CONGRÈS",
    signinAccount: "Se connecter à votre compte",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    createOneNow: "Créez-en un maintenant",
    welcomeBack: "Bienvenue,",
    dualRoleContext: "Votre profil détient plusieurs rôles. Veuillez choisir votre espace de travail :",
    partAuthorWorkspace: "Espace Auteur / Participant",
    partAuthorWorkspaceDesc: "Soumettez des articles, consultez le programme, regardez les posters et discutez.",
    revPanel: "Espace Évaluateur Académique",
    revPanelDesc: "Évaluez les articles assignés et soumettez vos grilles de relecture.",
    pscConsoleTitle: "Espace Président du Comité Scientifique",
    pscConsoleDesc: "Gérez les thématiques, assignez les relecteurs et validez les rapports.",
    presConsoleTitle: "Espace Président de l'Organisation (POC)",
    presConsoleDesc: "Gérez la logistique, la charte graphique et générez les badges.",
    superadminConsoleTitle: "Espace Administrateur Global SaaS",
    superadminConsoleDesc: "Gérez les conférences, les connexions et les comptes administrateurs."
  },

  en: {
    // ── Navbar / Generic ─────────────────────────────────────────────────────
    landingPage: "Congress Landing",
    workspaceDashboard: "Workspace & Dashboard",
    signOut: "Sign Out",
    signIn: "Sign In",
    register: "Register Account",
    role: "Role",
    status: "Status",
    welcome: "Welcome",
    contextSelector: "Work Context",
    notifications: "Notifications",
    pendingMeetings: "pending meeting requests",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    search: "Search",
    export: "Export",
    import: "Import",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    confirm: "Confirm",
    close: "Close",
    send: "Send",
    assign: "Assign",
    validate: "Validate",
    reject: "Reject",
    approve: "Approve",
    download: "Download",
    upload: "Upload",
    preview: "Preview",
    submit: "Submit",
    actions: "Actions",
    loading: "Loading...",
    noResults: "No results found.",
    
    // ── Status Labels ─────────────────────────────────────────────────────────
    statusSubmitted: "Initial Submission",
    statusUnderReview: "Under Review",
    statusReviewed: "Reviewed",
    statusReviewDispatched: "Review Report Dispatched",
    statusRevisionSubmitted: "Revision Submitted",
    statusAccepted: "Accepted",
    statusRejected: "Rejected",
    statusPending: "Pending",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusOpen: "Open",
    statusClosed: "Closed",
    statusApproved: "Approved",
    
    // ── Auth Modal ────────────────────────────────────────────────────────────
    loginTitle: "Sign In",
    registerTitle: "Register",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    nameLabel: "Full Name",
    affiliationLabel: "Affiliation Institution",
    roleLabel: "Requested Role",
    conferenceLabel: "Select Conference Track",
    submitBtn: "Submit",
    loginError: "Incorrect email or password.",
    loginSuccess: "Login successful!",
    authTitle: "Sympovex Authentication",
    awaitingValTitle: "Awaiting Validation",
    awaitingValDesc: "Your account registration request is pending validation by the administrator. You will be able to sign in once activated.",
    submitReg: "Submit Registration",
    regSuccessTitle: "Registration Request Received",
    regSuccessDesc: "Your account registration has been successfully recorded. An administrator will review and validate it before you can log in.",
    createAccount: "Create Account",
    
    // ── Dashboard Hub ─────────────────────────────────────────────────────────
    accessRestricted: "Workspace Access Restricted",
    selectRoleTitle: "Select Workspace Environment",
    enterWorkspace: "Enter Workspace",
    forcePasswordTitle: "Define New Password",
    forcePasswordDesc: "Your account was created by an administrator. You must set a new password before continuing.",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm Password",
    passwordMismatch: "Passwords do not match.",
    passwordTooShort: "Password must be at least 8 characters long.",
    passwordChanged: "Password updated successfully.",
    
    // ── Participant / Author Dashboard ────────────────────────────────────────
    participantConsole: "Author & Participant Workspace",
    participantDesc: "Submit research papers, upload revisions, interact with attendees, and track submission status.",
    newSubmission: "New Paper Submission",
    paperTitle: "Paper Title",
    abstract: "Abstract Summary",
    keywords: "Keywords",
    authorsList: "Authors Matrix",
    paperType: "Submission Format",
    shortPaper: "Short Paper",
    extendedPaper: "Extended Paper",
    poster: "Poster",
    submitSuccess: "Your scientific manuscript was submitted successfully!",
    submitSuccessId: "Registered Reference:",
    submitSuccessEmail: "A confirmation email has been sent to your address.",
    mySubmissions: "My Submissions & Status",
    proceedingsDownload: "Official Congress Proceedings",
    proceedingsDesc: "Download the full collection of accepted papers and official abstract proceedings.",
    proceedingsBtn: "Download Proceedings",
    submissionGuidelines: "Submission Guidelines",
    selectTopics: "Scientific Topics (select at least 1)",
    attachFile: "Attach manuscript file (.pdf, .docx, .tex)",
    addAuthor: "Add Author",
    removeAuthor: "Remove",
    authorName: "Author Name",
    authorAffiliation: "Institution",
    authorEmail: "Author Email",
    fileError: "Invalid file type. Accepted: .pdf, .docx, .tex, .doc",
    
    // ── Participant — Review dispatch banner ──────────────────────────────────
    reviewDispatchedBanner: "📩 The Scientific Committee has validated and sent your evaluation report.",
    reviewDispatchedAction: "You may now submit a corrected version of your manuscript.",
    uploadRevisionBtn: "Upload Corrected Version",
    uploadRevisionTitle: "Revised Version Upload",
    uploadRevisionSuccess: "Revision V{n} registered successfully! The committee has been notified.",
    
    // ── Participant — Survey ──────────────────────────────────────────────────
    surveyTitle: "Satisfaction Questionnaire",
    surveyDesc: "Share your experience with the organizing committee.",
    surveyOrgLabel: "Organization & Logistics (1–5)",
    surveyContentLabel: "Scientific Quality & Content (1–5)",
    surveyCommentsLabel: "Free-text comments",
    surveySubmitBtn: "Submit My Feedback",
    surveySuccess: "Thank you! Your questionnaire has been recorded.",
    
    // ── Participant — Gallery ─────────────────────────────────────────────────
    galleryUpload: "Upload Live Event Photos",
    galleryDesc: "Share event photos (subject to committee moderation).",
    galleryCaptionLabel: "Photo caption",
    gallerySubmitBtn: "Submit for moderation",
    gallerySuccess: "Photo submitted! Awaiting approval.",
    
    // ── Participant — Vote ────────────────────────────────────────────────────
    voteTitle: "Public Voting Grid",
    bestPosterVote: "Vote for Best Poster Design",
    bestOralVote: "Vote for Best Oral Presentation",
    voteSuccess: "Your vote has been recorded!",
    alreadyVoted: "You have already voted in this category.",
    
    // ── Participant — Networking ──────────────────────────────────────────────
    networkingTitle: "Networking & Messaging",
    chatWith: "Chat with",
    sendMessage: "Send message",
    scheduleSlot: "Schedule a meeting",
    meetingPurpose: "Meeting purpose",
    meetingDate: "Preferred date/time",
    scheduleMeetingBtn: "Request a slot",
    meetingSuccess: "Meeting request sent!",
    
    // ── Participant — Tickets ─────────────────────────────────────────────────
    supportTickets: "My Support Tickets",
    newTicket: "New Ticket",
    ticketSubject: "Ticket subject",
    ticketCategory: "Category",
    ticketMessage: "Detailed message",
    ticketSubmitBtn: "Submit ticket",
    ticketSuccess: "Ticket opened successfully.",
    ticketReply: "Reply",
    
    // ── Reviewer Dashboard ────────────────────────────────────────────────────
    reviewerConsole: "Academic Reviewer Panel",
    reviewerDesc: "Review your assigned manuscripts, submit detailed evaluation reports, and track progress.",
    assignedPapers: "Assigned Manuscripts",
    evaluateBtn: "Evaluate Manuscript",
    scoreCriteria: "Evaluation Criteria Details",
    commentsFormLabel: "Formatting & Style Remarks",
    commentsSciLabel: "Scientific & Technical Remarks",
    presentationFormat: "Recommended Presentation Format",
    oralFormat: "Oral Presentation",
    posterFormat: "Poster Presentation",
    attachCommentsFile: "Attach Comments File (.pdf / .docx)",
    reviewSubmitBtn: "Submit Evaluation Report",
    reviewSuccess: "Evaluation report submitted successfully!",
    alreadyReviewed: "You have already submitted a report for this manuscript.",
    noAssignedPapers: "No manuscripts have been assigned to you yet.",
    viewScoreCard: "View Score Card",
    readOnlyReview: "Review Submitted (Read Only)",
    closePane: "Close Pane",
    selectManuscriptPrompt: "Select an assigned manuscript from the left list to start your evaluation.",
    choosePhotoSubmit: "Choose a photo to submit",
    photoCaptionPlaceholder: "E.g. Plenary session or networking",
    noAssignedPapersTrack: "No manuscripts assigned to your track profile.",
    originalityNovelty: "Originality & Novelty",
    methodologyRigor: "Methodology & Rigor",

    // ── Global Portal ──────────────────────────────────────────────────────────
    portalTitle: "Premium SaaS Platform for Scientific Congresses",
    portalSub: "Manage submissions, conduct double-blind peer reviews, drive attendee networking, and track survey analytics in real-time.",
    activeCongresses: "Active Congresses",
    archivedCongresses: "Archived Congresses",
    enterCongress: "Enter Congress Site →",
    viewArchives: "View Archives",
    platformFeatures: "Platform Features",
    featureMultiTenant: "Multi-Tenant",
    featureMultiTenantDesc: "Host multiple independent congresses with isolated themes and database states.",
    featureTranslation: "Full Localization",
    featureTranslationDesc: "Dynamic real-time translation of all static and dynamic text content for global delegates.",
    featureReview: "Double-Blind Review",
    featureReviewDesc: "Smart reviewer assignment, consolidated reports, and validation pipeline for the program committee.",
    featureNetworking: "Networking & Gallery",
    featureNetworkingDesc: "Instant messaging, face-to-face meeting scheduling, and live interactive event galleries.",
    viewAllCongresses: "← All Congresses",
    profileTitle: "Your User Profile",
    profileSubtitle: "Update your personal information, profile photo, and biography.",
    profileName: "Full Name",
    profilePhotoUrl: "Profile Photo URL",
    profileBio: "Description / Biography",
    profileSaveBtn: "Save Changes",
    profileSuccess: "Your profile has been updated successfully!",
    profilePresetAvatars: "Or choose a preset avatar",
    backToDashboard: "← Back to Dashboard",
    profileRole: "Account Role",
    profileAffiliation: "Affiliation / University",
    
    // ── PSC Dashboard ─────────────────────────────────────────────────────────
    pscConsole: "Scientific Committee (PSC) Master Console",
    pscDesc: "Oversee the scientific pipeline, configure tracks, provision reviewers, and validate evaluation reports.",
    tabPapers: "Master Submissions",
    tabTopics: "Congress Topics CRUD",
    tabParticipants: "Participants Directory",
    tabReviewers: "Reviewer Control",
    tabTickets: "Support Queries",
    tabProvisioning: "Provision Accounts",
    tabGuidelines: "Guidelines & Criteria",
    
    // PSC — Paper table columns
    colTitleAuthors: "Title & Authors",
    colTopics: "Topics",
    colReviewers: "Reviewers",
    colAvgScore: "Avg. Score",
    colActions: "Actions",
    colStatus: "Status",
    colDate: "Date",
    colVersion: "Version",
    colFile: "File",
    
    // PSC — Paper detail drawer
    paperDetail: "Submission Detail",
    paperId: "Reference ID",
    paperSubmittedOn: "Submitted on",
    paperVersionHistory: "Version History",
    paperReviewHistory: "Full Review Timeline",
    paperReviewReports: "Consolidated Evaluation Reports",
    pscValidationPanel: "PSC Validation Panel",
    pscValidationNote: "PSC Validation Note (optional)",
    pscValidationNotePlaceholder: "Add a synthesis note visible to the author...",
    validateAndSendBtn: "Validate & Send Report to Author",
    rejectPaperBtn: "Reject Submission",
    reportAlreadySent: "✅ Report already dispatched to author.",
    noReviewsYet: "No evaluation reports received for this paper yet.",
    reviewerLabel: "Reviewer",
    formRemarks: "Formatting Remarks",
    scientificRemarks: "Scientific Remarks",
    recommendedFormat: "Recommended Format",
    overallScore: "Overall Score",
    dispatchSuccess: "Report validated and dispatched to author successfully!",
    dispatchConfirm: "Confirm dispatch of evaluation report to the author?",
    rejectConfirm: "Confirm permanent rejection of this submission?",
    
    // PSC — timeline event labels
    timelineSubmitted: "Submission received",
    timelineReviewerAssigned: "Reviewer(s) assigned",
    timelineReviewReceived: "Report received",
    timelineReportDispatched: "Report dispatched to author",
    timelineRevisionReceived: "Revision received",
    
    // PSC — side panel
    consolidatedReviews: "Consolidated Reports",
    noReviewsSidePanel: "No evaluations submitted yet.",
    
    // PSC — Topics
    topicsCrud: "Scientific Topics Track Management",
    topicName: "Topic Name",
    topicDescription: "Description (optional)",
    addTopicBtn: "Add Topic",
    editTopic: "Edit Topic",
    deleteTopicConfirm: "Delete this scientific topic?",
    noTopics: "No topics configured yet.",
    
    // PSC — Participants
    participantsDir: "Participants Directory",
    partSearchPlaceholder: "Search by name, email, institution...",
    promoteToReviewer: "Promote to Reviewer",
    alreadyReviewer: "Already a Reviewer",
    exportParticipants: "Export CSV",
    importParticipants: "Import Excel",
    noParticipants: "No participants found.",
    
    // PSC — Reviewer Control
    reviewerControl: "Reviewers Registry",
    assignPaper: "+ Assign",
    selectReviewer: "Select reviewer profile...",
    commitAssignment: "Commit Assignment",
    noReviewers: "No reviewers registered.",
    
    // PSC — Provisioning
    provisionAccounts: "Provision Active Accounts",
    provFullName: "Full Name",
    provEmail: "Email Address",
    provRole: "Role",
    provAffiliation: "Institution",
    provPassword: "Temporary Password",
    provBtn: "Create Account",
    provSuccess: "Account created. User will be forced to change their password on first login.",
    
    // PSC — Provisioning Bulk
    bulkProvisionTitle: "Bulk Provisioning (Excel/CSV)",
    bulkProvisionDesc: "Import a list of users from an Excel/CSV file or export existing accounts.",
    downloadTemplate: "Download Template (.csv)",
    importPlaceholder: "Drag & drop or select a CSV file...",
    importFileBtn: "Choose File",
    importSubmitBtn: "Import & Provision",
    exportPartBtn: "Export Participants",
    exportRevBtn: "Export Reviewers",
    exportAllBtn: "Export All Accounts",
    importReportSuccess: "Import successful! {count} accounts provisioned.",
    importReportError: "Import failed: {error}",
    
    // PSC — Guidelines & Criteria
    authorInstructions: "Author Submission Guidelines",
    authorInstructionsPlaceholder: "Write the submission guidelines (format, length, style...).",
    saveGuidelines: "Save Guidelines",
    guidelinesSaved: "Guidelines updated successfully.",
    evaluationCriteria: "Scientific Evaluation Criteria",
    critName: "Criterion Name",
    critMaxScore: "Max Score",
    addCritBtn: "Add Criterion",
    noCriteria: "No criteria configured.",
    deleteCritConfirm: "Delete this evaluation criterion?",
    
    // ── POC Dashboard ──────────────────────────────────────────────────────────
    pocConsole: "Organizing Committee (POC) Dashboard",
    pocDesc: "Manage organization, analyze survey feedback, segment contacts, and generate badges.",
    satisfactionAnalytics: "Satisfaction Survey Analytics & Charts",
    avgOrgRating: "Avg. Organization",
    avgContentRating: "Avg. Scientific Content",
    surveyResponses: "response(s)",
    segmentationDb: "Contacts Database Segmentation",
    filterBySegment: "Filter by segment",
    allSegments: "All segments",
    exportFiltered: "Export segment CSV",
    attestationBadge: "Badges & Attestations Mail Merge",
    selectTemplate: "Select template",
    generateBtn: "Generate for all participants",
    exportMerge: "Export mail merge",
    voteLeaderboard: "Public Votes Live Leaderboard",
    bestPoster: "Best Poster",
    bestPresentation: "Best Presentation",
    votes: "vote(s)",
    mailingCampaigns: "Email Campaigns",
    galleryModeration: "Gallery Moderation Board",
    approvePhoto: "Approve",
    deletePhoto: "Delete",
    pendingPhotos: "Pending photos",
    noPhotos: "No photos submitted.",
    
    // ── Admin / President Dashboard ────────────────────────────────────────────
    adminConsole: "Congress President Console",
    adminDesc: "Manage registrations, graphic identity, and content moderation.",
    brandingConfig: "Dynamic Graphic Branding Identity",
    primaryColor: "Primary Color",
    secondaryColor: "Secondary Color",
    accentColor: "Accent Color",
    applyBranding: "Apply Branding",
    pendingValidations: "Moderation of Pending Registrations",
    activateUser: "Activate",
    suspendUser: "Suspend",
    deleteUserConfirm: "Delete this user?",
    
    // ── Superadmin Dashboard ───────────────────────────────────────────────────
    superadminConsole: "Superadmin Console — Global Administration",
    superadminDesc: "Manage all congresses, all users, Supabase connections and system configuration.",
    supabaseConfig: "Supabase Connection Configuration",
    supabaseUrl: "Supabase URL",
    supabaseKey: "Anonymous Key (Anon Key)",
    supabaseJwt: "JWT Secret",
    exportSqlSchema: "Export SQL Schema",
    resetDatabase: "Reset Database",
    resetConfirm: "Confirm reset? All data will be permanently deleted.",
    
    // ── Workspace & Dashboard Hub ──
    pwErrorLength: "Password must be at least 6 characters.",
    pwErrorMatch: "Passwords do not match.",
    pwErrorFail: "Failed to change password. Please contact support.",
    secureInterface: "SECURE WORKSPACE INTERFACE",
    sessionRole: "SESSION ROLE",
    tenantLabel: "TENANT",
    signinAccount: "Sign In to Account",
    dontHaveAccount: "Don't have an account?",
    createOneNow: "Create one now",
    welcomeBack: "Welcome back,",
    dualRoleContext: "Your profile holds multiple role contexts. Please select your workspace environment:",
    partAuthorWorkspace: "Participant / Author Workspace",
    partAuthorWorkspaceDesc: "Submit papers, check schedules, view E-posters, and message other delegates.",
    revPanel: "Academic Reviewer Panel",
    revPanelDesc: "Access assigned papers, evaluate submissions, and log review score cards.",
    pscConsoleTitle: "PSC Program Chair Console",
    pscConsoleDesc: "Manage tracks, assign reviewers, validate papers, and oversee participants.",
    presConsoleTitle: "President / POC Console",
    presConsoleDesc: "Configure details, brand colors, speakers list, and generate mail merge.",
    superadminConsoleTitle: "Superadmin Platform Hub",
    superadminConsoleDesc: "Global SaaS administration: provision conference tenants and assign credentials."
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('sympovex_lang') || 'fr');

  useEffect(() => {
    localStorage.setItem('sympovex_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
